# Generated by Django 5.0.7 on 2024-07-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishlist", "0002_wishlist_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist",
            old_name="quantity",
            new_name="product_quantity",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="date",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="product",
        ),
        migrations.AddField(
            model_name="wishlist",
            name="product_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="product_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="product_image",
            field=models.CharField(
                blank=True, default="product.jpg", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="product_price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="product_subtotal",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="product_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
