# Generated by Django 5.0.7 on 2024-07-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0002_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
