# Generated by Django 5.0.7 on 2024-07-26 07:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0004_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="image_profile",
            new_name="image",
        ),
    ]
