# Generated by Django 5.0.7 on 2024-07-26 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0005_rename_image_profile_userprofile_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
