# Generated by Django 5.0.7 on 2024-07-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0008_alter_userprofile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address1",
            field=models.CharField(default="Address 1", max_length=255),
        ),
        migrations.AlterField(
            model_name="address",
            name="address2",
            field=models.CharField(
                blank=True, default="Address 2", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(
                blank=True, default="City", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(
                blank=True, default="Country", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="first_name",
            field=models.CharField(default="First name", max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="last_name",
            field=models.CharField(default="Last name", max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="phone",
            field=models.CharField(default="Phone", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="zipcode",
            field=models.CharField(blank=True, default="000", max_length=20, null=True),
        ),
    ]
