# Generated by Django 5.0.7 on 2024-07-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0009_alter_address_address1_alter_address_address2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, default="Bio", null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(default="First name", max_length=200),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(
                blank=True, default="Last name", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, default="12345678", max_length=100),
        ),
    ]
