# Generated by Django 5.0.7 on 2024-07-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "userauths",
            "0010_alter_userprofile_bio_alter_userprofile_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(default="default.png", upload_to="userprofile/"),
        ),
    ]
