# Generated by Django 5.0.7 on 2024-07-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0011_alter_userprofile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                default="userprofile/default.png", upload_to="userprofile/"
            ),
        ),
    ]
