# Generated by Django 5.0.7 on 2024-07-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0012_alter_userprofile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="userprofile/default.png",
                null=True,
                upload_to="userprofile/",
            ),
        ),
    ]
