# Generated by Django 5.0.7 on 2024-07-26 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0013_alter_userprofile_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
