# Generated by Django 5.0.7 on 2024-07-26 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0014_delete_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(default="First name", max_length=200)),
                (
                    "last_name",
                    models.CharField(
                        blank=True, default="Last name", max_length=200, null=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="userprofile/default.png",
                        null=True,
                        upload_to="userprofile/",
                    ),
                ),
                ("bio", models.TextField(blank=True, default="Bio", null=True)),
                ("verified", models.BooleanField(default=False)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="12345678", max_length=100),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
