# Generated by Django 5.0.3 on 2024-06-09 18:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_vendor_date_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="cover_image",
            field=models.ImageField(
                default="vendor.jpg", upload_to=core.models.user_directory_path
            ),
        ),
    ]
