# Generated by Django 5.0.3 on 2024-06-10 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_vendor_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="life",
            field=models.CharField(
                blank=True, default="100 Days", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="manufactured",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                blank=True, default="Ornganic", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_images",
                to="core.product",
            ),
        ),
    ]
