# Generated by Django 5.0.3 on 2024-06-10 14:25

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_product_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, default="This is a product", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="specifications",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, default="Specification", null=True
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, default="I am a vendor", null=True
            ),
        ),
    ]
