# Generated by Django 5.0.7 on 2024-07-23 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_productreview_product"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WishList",
        ),
    ]
