# Generated by Django 5.0.7 on 2024-07-23 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_delete_wishlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartorderitem",
            name="order",
        ),
        migrations.DeleteModel(
            name="CartOrder",
        ),
        migrations.DeleteModel(
            name="CartOrderItem",
        ),
    ]
