# Generated by Django 5.0.7 on 2024-07-24 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_remove_cartorderitem_order_delete_cartorder_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
    ]
