# Generated by Django 5.0.7 on 2024-07-26 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name_plural": "ContactUs"},
        ),
    ]
