# Generated by Django 5.0.7 on 2024-07-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_cart_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="product_subtotal",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
