# Generated by Django 5.0.7 on 2024-07-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_cart_product_subtotal"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="product_image",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
