# Generated by Django 5.0.7 on 2024-07-23 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0005_alter_cart_product_image"),
        ("core", "0010_remove_cartorderitem_order_delete_cartorder_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="product_category",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="product_id",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="product_image",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="product_price",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="product_title",
        ),
        migrations.AddField(
            model_name="cart",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.product",
            ),
        ),
    ]
