# Generated by Django 5.0.7 on 2024-07-23 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_order_product_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
