# Generated by Django 5.0.7 on 2024-07-23 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="order.payment",
            ),
        ),
    ]
