# Generated by Django 5.0.7 on 2024-07-23 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0008_remove_orderitem_order_delete_order_delete_orderitem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
