# Generated by Django 5.0.7 on 2024-07-23 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0010_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payement",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
