# Generated by Django 5.0.7 on 2024-07-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0013_orderproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="image",
            field=models.ImageField(upload_to="order_items/"),
        ),
    ]
