# Generated by Django 5.0.7 on 2024-07-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0014_alter_orderitem_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="image",
            field=models.CharField(max_length=200),
        ),
    ]
