# Generated by Django 5.0.7 on 2024-07-25 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0016_order_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="payement",
            new_name="payment",
        ),
    ]
